# -*- mode: makefile -*-

NAME= umllm
AUTHOR= PUC-Behring Institute for AI
EMAIL= glima@puc-rio.br
URL= https://github.com/PUC-Behring-Institute-for-AI/umllm
URL_SSH= git@github.com:PUC-Behring-Institute-for-AI/umllm

COPYRIGHT= PUC-Rio/PUC-Behring Institute for AI
COPYRIGHT_START_YEAR= 2026
LICENSE= Apache-2.0

SETUP_PY_CLASSIFIERS= [\
    'Programming Language :: Python',\
    'Programming Language :: Python :: 3',\
    'Programming Language :: Python :: 3.9',\
    'Programming Language :: Python :: 3.10',\
    'Programming Language :: Python :: 3.11',\
    'Programming Language :: Python :: 3.12',\
    'Programming Language :: Python :: 3.13',\
    'Programming Language :: Python :: 3.14',\
  ]

SETUP_PY_PACKAGE_DATA= {\
    '${PACKAGE}': ['py.typed'],\
  }

SETUP_PY_ENTRY_POINTS= {\
    'console_scripts': ['umllm = umllm.cli:cli'],\
  }

SETUP_PY_INSTALL_REQUIRES= [\
    'click',\
    'flask',\
    'langchain-core',\
    'langchain-google-genai',\
    'langchain-ollama',\
    'langchain-openai',\
    'types-click',\
    'typing-extensions',\
  ]

CHECK_PYLINT= no
CHECKFAST= ${TOX_SETENV}
ISORT_CFG_ADD_IMPORTS= from __future__ import annotations
MYPY_OPTIONS=
PYLINT_OPERANDS= ${PACKAGE}
TOX_INI_EXTRAS= all
